version: '3.8'

services:
  wordpress:
    image: wordpress:6.7-php8.2-apache
    container_name: clearcv-blog-local
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress_pass
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wordpress-data:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: clearcv-blog-db
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress_pass
      MYSQL_ROOT_PASSWORD: root_pass
    volumes:
      - ./db-data:/var/lib/mysql
